name: github workflow actions
on: push
jobs: 
    job1:  
        runs-on: ubuntu-latest
        steps: 
            - name: linux commands
              run:  sudo apt update
            - name: linux commands
              run: sudo apt install vim
